"""
generate_reports_data.py
Read final_risk_reports.jsonl and emit reports_data.js so that
dashboard.html can display pipeline results without a web server.

Usage:
    python generate_reports_data.py
    python generate_reports_data.py --input my_reports.jsonl --output my_data.js
"""

import json
import argparse
import sys
from datetime import datetime

INPUT_FILE  = "final_risk_reports.jsonl"
OUTPUT_FILE = "reports_data.js"

# Fields to include in the JS payload (drop heavy embedding arrays)
KEEP_FIELDS = {
    "pipeline_version", "run_timestamp",
    "question", "category", "model",
    "num_samples", "num_paraphrases",
    "uncertainty_score", "consistency_score", "calibration_score",
    "risk_score", "risk_zone", "severity",
    "window_key", "drift_score", "drift_alert", "drift_severity",
    "change_point", "delta_uncertainty", "delta_consistency",
    "cluster_id", "alerts", "alert_count", "execution_time_seconds",
}


def load_reports(path):
    records = []
    try:
        with open(path, "r", encoding="utf-8") as f:
            for i, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                try:
                    records.append(json.loads(line))
                except json.JSONDecodeError as e:
                    print(f"  [WARN] Skipping malformed line {i}: {e}", file=sys.stderr)
    except FileNotFoundError:
        print(f"  [WARN] '{path}' not found — writing empty data file.", file=sys.stderr)
    return records


def slim(record):
    """Return a copy of record with only dashboard-relevant fields."""
    return {k: v for k, v in record.items() if k in KEEP_FIELDS}


def write_js(records, path):
    slimmed = [slim(r) for r in records]
    js_payload = json.dumps(slimmed, ensure_ascii=False, indent=2)
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    content = (
        f"// Auto-generated by generate_reports_data.py — {ts}\n"
        f"// {len(records)} pipeline report(s) from final_risk_reports.jsonl\n"
        f"window.REPORTS_DATA = {js_payload};\n"
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  Written {len(records)} record(s) → '{path}'")


def main():
    parser = argparse.ArgumentParser(description="Generate reports_data.js for dashboard")
    parser.add_argument("--input",  default=INPUT_FILE)
    parser.add_argument("--output", default=OUTPUT_FILE)
    args = parser.parse_args()

    print(f"\n  Reading  : {args.input}")
    records = load_reports(args.input)
    print(f"  Records  : {len(records)}")

    write_js(records, args.output)
    print(f"\n  Done. Open dashboard.html in a browser to view pipeline results.")


if __name__ == "__main__":
    main()